make all:
	gcc remetteur.cpp -o remetteur       `pkg-config --cflags opencv`       `pkg-config --libs opencv` -lpthread
	gcc emetteur.cpp -o emetteur       `pkg-config --cflags opencv`       `pkg-config --libs opencv` -lpthread
